[package]
name = "assertify"
version = "0.6.0"
authors = ["Daniel Parks <oss-assertify@demonhorse.org>"]
description = "Make tests from simple expressions with easy to understand failures"
homepage = "https://github.com/danielparks/assertify"
repository = "https://github.com/danielparks/assertify"
readme = "README.md"
keywords = ["test", "assert"]
categories = ["development-tools::testing"]
license = "MIT OR Apache-2.0"
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
assertify_proc_macros = { version = "0.6.0", path = "assertify_proc_macros" }
proc-macro-hack = "0.5"

[dev-dependencies]
trybuild = "1.0"
