[package]
name = "assertify"
version = "0.1.0"
authors = ["Daniel Parks <oss-assertify@demonhorse.org>"]
description = "Make tests from simple expressions without boilerplate"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
assertify_proc_macros = { version = "*", path = "assertify_proc_macros" }
proc-macro-hack = "0.5"
